### ISSUE TITLE
Tip: When creating new stuff..

### ISSUE THREAD

**Issue by Arkkimaagi** [rafaelconde/ios8-ui-kit#5]
Thank you for the great resource!

I had an idea for if you want to add more content and do not want to take screenshots yourself. Check out if this helps:
http://mercury.io/blog/ios-8-illustrator-vector-ui-kit-update

It's sadly not in Sketch format, but it's the most extensive resource I've found so far. I do not mean that you should do everything in it, more like use it as a reference. :)

**Comment by rafaelconde** [comment]
Thanks Mikko,

Those guys did an awesome job, no doubt about it, and I got some ideas for elements to add in the future from them.

Thanks for sharing 👍

—
Rafa
