### ISSUE TITLE
Unable to open .sketch file

### ISSUE THREAD

**Issue by Cara-Jo** [rafaelconde/ios8-ui-kit#7]
Getting an error when trying to open file from repository.

![screenshot 2014-10-02 14 11 11](https://cloud.githubusercontent.com/assets/180763/4497578/530459ea-4a70-11e4-8dd2-9bad865ad191.png)

**Comment by rafaelconde** [comment]
Hum... opens just fine here on my machine. Are you running the latest version of Sketch (3.1)?

**Comment by chrysb** [comment]
I was having the same issue. Upgrading to 3.1 fixes this.

**Comment by rafaelconde** [comment]
I'll update the README file to say that 3.1 is required. Thanks guys 👍
